### ISSUE TITLE
Press Pagination

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/czech#1]
Need to make it so that there are 9 press items per page. Need to add pagination. Do I need to design what that looks like?

**Comment by xtinarees** [comment]
@rickyferrer if I paginate the press page I can't make the press items sortable by category (unless when you click on a category it takes you to a separate page). If you want to keep the sorting function within the one page, I can add lazy loading images. If not, I can paginate.

**Comment by xtinarees** [comment]
nevermind, the sorting is on the other sites, not this one. I'll just paginate.
