### ISSUE TITLE
Sort by option? 

### ISSUE THREAD

**Issue by rickyferrer** [xtinarees/czech#13]
alphabetical, price, popular?

**Comment by xtinarees** [comment]
@rickyferrer there is not an easy way to do this. it is possible but I think it will take a while. would you still like me to do it?

**Comment by rickyferrer** [comment]
what about a plugin like https://wordpress.org/plugins/woocommerce-extra-product-sorting-options/screenshots/

**Comment by xtinarees** [comment]
@rickyferrer just tried this plugin but it didnt work. I'll see if I can find another one.
