### ISSUE TITLE
sorting woocommerce products by category is complex

### ISSUE THREAD

**Issue by xtinarees** [xtinarees/czech#8]
@rickyferrer
there is this plugin: http://codecanyon.net/item/woocommerce-product-filter/8514038
which is cheaper than me building something from scratch myself.
Or let me know if you've done this (category product filter) in the past and how.

**Comment by xtinarees** [comment]
I cant just use filtering code that we've used the past (like on interactives) bc it has to work w/ woocommerce which uses its own hooks, classes, filtering system, etc.

**Comment by rickyferrer** [comment]
This is the site I did that used woocommerce: http://www.onestoneshop.com/product-category/rings/

**Comment by rickyferrer** [comment]
But I say if we can just buy something that's quick and easy, let's do that.
